blueprint:
  name: 💡 Akwarium – Światła + CO₂ + Karmienie + Serwis
  description: >
    Kompletny blueprint automatyzacji akwarium:
    • Automatyczne rampy jasności dla 4 kanałów światła
    • CO₂ – włącza się z pierwszym światłem i wyłącza 30 min przed końcem
    • Tryb karmienia – zatrzymuje filtr, włącza timer i przywraca po zakończeniu
    • Tryb serwisowy – wszystkie światła 90%, filtr OFF, zapis i przywrócenie stanu
  domain: automation
  author: ChatGPT (GPT-5)
  source_url: https://github.com/GieOeRZet/akwarium/blob/main/akwarium.yaml
  # ... (reszta blueprintu jak w poprzedniej wiadomości)
