blueprint:
  name: 💡 Podbitka + Podjazd – Automatyczne światła (Brama + Drzwi)
  description: >
    Kompleksowa automatyzacja oświetlenia zewnętrznego:
    - Podbitka włącza się po zmierzchu i wyłącza o 22:00 etapami
    - Rano o 6:00 włącza się, jeśli nadal ciemno
    - Wyłącza się przy pełnym dniu
    - Osobne światła i czas świecenia po otwarciu bramy lub drzwi
    - Licznik czasu resetuje się przy ponownym otwarciu bramy lub drzwi
    - Pomija działanie, gdy input_boolean.swieta = ON

  domain: automation
  source_url: "https://raw.githubusercontent.com/GieOeRZet/akwarium/main/blueprints/automation/gieoerzet/swiatla_zewnetrzne.yaml"

  input:
    podbitka_all:
      name: 💡 Światła podbitki – całość
      description: Główna grupa lub światła do włączania/wyłączania całości.
      selector:
        entity:
          domain: light

    podbitka_srodki:
      name: 💡 Światła – środki
      description: Światła środkowe do wyłączenia o 22:00.
      selector:
        entity:
          domain: light

    podbitka_rogi:
      name: 💡 Światła – rogi
      description: Światła rogowe do wyłączenia 30 minut po 22:00.
      selector:
        entity:
          domain: light

    podjazd_swiatlo:
      name: 🚗 Światło podjazdu
      description: Oświetlenie podjazdu lub ścieżki – może być użyte przy bramie lub drzwiach.
      selector:
        entity:
          domain: light

    czujnik_drzwi:
      name: 🚪 Czujnik drzwi wejściowych
      description: Sensor otwarcia drzwi wejściowych (binary_sensor).
      selector:
        entity:
          domain: binary_sensor

    brama:
      name: 🚧 Brama wjazdowa
      description: Encja bramy (cover), która uruchamia światła po otwarciu.
      selector:
        entity:
          domain: cover

    czujnik_dnia:
      name: 🌅 Sensor okresu dnia
      description: Sensor np. sensor.period_of_day z wartościami daylight / nightlight / dawnlight / dusklight.
      selector:
        entity:
          domain: sensor

    swieta:
      name: 🎄 Przełącznik „Święta”
      description: Nie uruchamiaj automatyzacji, jeśli włączony.
      selector:
        entity:
          domain: input_boolean

    godzina_off:
      name: 🕙 Godzina wyłączenia wieczorem
      default: "22:00:00"
      selector:
        time: {}

    godzina_rano:
      name: 🌅 Godzina włączenia rano
      default: "06:00:00"
      selector:
        time: {}

    # --- NOWE INPUTY (z podpowiedziami) ---
    swiatla_bramy:
      name: 💡 Światła zapalane po otwarciu bramy
      description: >
        Wybierz spośród wcześniej dodanych świateł (np. podbitka, podjazd),
        które mają się zapalać przy otwieraniu bramy.
      default: !input podbitka_all
      selector:
        target:
          entity:
            domain: light

    swiatla_drzwi:
      name: 💡 Światła zapalane po otwarciu drzwi
      description: >
        Wybierz spośród wcześniej dodanych świateł (np. podjazd),
        które mają się zapalać przy otwieraniu drzwi wejściowych.
      default: !input podjazd_swiatlo
      selector:
        target:
          entity:
            domain: light

    czas_bramy:
      name: ⏱️ Czas świecenia po otwarciu bramy (min)
      description: Po ilu minutach wyłączyć światła zapalone przez bramę.
      default: 5
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: min
          mode: slider

    czas_drzwi:
      name: ⏱️ Czas świecenia po otwarciu drzwi (min)
      description: Po ilu minutach wyłączyć światła zapalone przez drzwi.
      default: 5
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: min
          mode: slider

mode: restart

triggers:
  - platform: state
    entity_id: !input czujnik_dnia
    from: daylight
    id: PodbitkaON

  - platform: state
    entity_id: !input czujnik_dnia
    to: daylight
    id: PodbitkaDaylightOFF

  - platform: time
    at: !input godzina_off
    id: PodbitkaOFF

  - platform: time
    at: !input godzina_rano
    id: PodbitkaRANO

  - platform: state
    entity_id: !input brama
    to: opening
    id: BramaOPEN

  - platform: state
    entity_id: !input czujnik_drzwi
    to: "on"
    id: DrzwiOPEN

conditions:
  - condition: state
    entity_id: !input swieta
    state: "off"

actions:
  - choose:
      # ---- WIECZOREM po zmierzchu ----
      - conditions:
          - condition: trigger
            id: PodbitkaON
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input podbitka_all

      # ---- O 22:00 – wyłączenie etapowe ----
      - conditions:
          - condition: trigger
            id: PodbitkaOFF
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input podbitka_srodki
          - delay: "00:30:00"
          - service: light.turn_off
            target:
              entity_id: !input podbitka_rogi

      # ---- RANO o 6:00 (jeśli ciemno) ----
      - conditions:
          - condition: trigger
            id: PodbitkaRANO
          - condition: or
            conditions:
              - condition: state
                entity_id: !input czujnik_dnia
                state: nightlight
              - condition: state
                entity_id: !input czujnik_dnia
                state: dawnlight
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input podbitka_all

      # ---- WYŁĄCZ przy pełnym dniu ----
      - conditions:
          - condition: trigger
            id: PodbitkaDaylightOFF
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input podbitka_all

      # ---- OTWARCIE BRAMY (nocą) ----
      - conditions:
          - condition: trigger
            id: BramaOPEN
          - condition: or
            conditions:
              - condition: state
                entity_id: !input czujnik_dnia
                state: nightlight
              - condition: state
                entity_id: !input czujnik_dnia
                state: dawnlight
              - condition: state
                entity_id: !input czujnik_dnia
                state: dusklight
        sequence:
          - service: light.turn_on
            target: !input swiatla_bramy
          - delay:
              minutes: !input czas_bramy
          - service: light.turn_off
            target: !input swiatla_bramy

      # ---- OTWARCIE DRZWI (nocą) ----
      - conditions:
          - condition: trigger
            id: DrzwiOPEN
          - condition: or
            conditions:
              - condition: state
                entity_id: !input czujnik_dnia
                state: nightlight
              - condition: state
                entity_id: !input czujnik_dnia
                state: dawnlight
              - condition: state
                entity_id: !input czujnik_dnia
                state: dusklight
        sequence:
          - service: light.turn_on
            target: !input swiatla_drzwi
          - delay:
              minutes: !input czas_drzwi
          - service: light.turn_off
            target: !input swiatla_drzwi
