blueprint:
  name: 💡 Podbitka – Automatyczne światła (pełny cykl dobowy)
  description: >
    Kompleksowa automatyzacja oświetlenia zewnętrznego:
    - Wieczorem zapala podbitkę (rogi + środki), gasi etapami o ustalonych godzinach.
    - Rano ponownie zapala podbitkę, jeśli jeszcze ciemno.
    - Reaguje na otwarcie bramy i drzwi (osobne czasy świecenia).
    - Automatycznie blokuje reakcje dzienne.
    - Tryb „Święta” dezaktywuje automatyzacje podbitki.
    - Wszystkie czasy i encje konfigurowalne z GUI.

  domain: automation
  source_url: "https://raw.githubusercontent.com/GieOeRZet/HA_BLUEPRINTS/main/blueprints/automation/gieoerzet/swiatla_zewnetrzne.yaml"

  input:
    czujnik_dnia:
      name: 🌅 Sensor okresu dnia
      description: Sensor określający porę dnia (np. sensor.period_of_day)
      selector:
        entity:
          domain: sensor

    podbitka_rogi:
      name: 💡 Światła podbitki – rogi
      description: Światła rogowe podbitki.
      selector:
        entity:
          domain: light

    podbitka_srodki:
      name: 💡 Światła podbitki – środki
      description: Światła środkowe podbitki.
      selector:
        entity:
          domain: light

    podjazd:
      name: 🚗 Światła podjazdu
      description: Oświetlenie podjazdu.
      selector:
        entity:
          domain: light

    brama:
      name: 🚪 Brama wjazdowa
      description: Encja bramy (cover), która wyzwala światła przy otwarciu.
      selector:
        entity:
          domain: cover

    drzwi:
      name: 🚪 Drzwi wejściowe
      description: Czujnik drzwi (binary_sensor), który wyzwala światła przy otwarciu.
      selector:
        entity:
          domain: binary_sensor

    swieta:
      name: 🎄 Przełącznik „Święta”
      description: Jeśli włączony, automatyzacja podbitki jest nieaktywna.
      selector:
        entity:
          domain: input_boolean

    # --- Parametry czasowe ---
    godzina_podbitka_srodki_off:
      name: 🕙 Godzina wyłączenia świateł podbitki – środki
      default: "22:00:00"
      selector:
        time: {}

    godzina_podbitka_rogi_off:
      name: 🕥 Godzina wyłączenia świateł podbitki – rogi
      default: "22:30:00"
      selector:
        time: {}

    godzina_podbitka_rano:
      name: 🌅 Godzina aktywacji podbitki rano
      default: "06:00:00"
      selector:
        time: {}

    czas_swiecenia_podbitki:
      name: ⏱️ Czas świecenia świateł podbitki (min)
      default: 5
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: min
          mode: slider

    czas_swiecenia_podjazdu:
      name: ⏱️ Czas świecenia świateł podjazdu (min)
      default: 5
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: min
          mode: slider

mode: parallel

triggers:
  # Wieczór → włączenie podbitki
  - platform: state
    entity_id: !input czujnik_dnia
    from: daylight
    id: PodbitkaON

  # Poranek → zmiana nightlight
  - platform: state
    entity_id: !input czujnik_dnia
    from: nightlight
    id: PodbitkaNightToDawn

  # Godzina 6:00 → alternatywna aktywacja rano
  - platform: time
    at: !input godzina_podbitka_rano
    id: PodbitkaRANO

  # Otwarcie bramy
  - platform: state
    entity_id: !input brama
    to: opening
    id: BramaOPEN

  # Otwarcie drzwi
  - platform: state
    entity_id: !input drzwi
    to: "on"
    id: DrzwiOPEN

  # Blokada dzienna (świt)
  - platform: state
    entity_id: !input czujnik_dnia
    from: dawnlight
    to: daylight
    id: BlokadaDziennaON

  # Odblokowanie wieczorem
  - platform: state
    entity_id: !input czujnik_dnia
    from: daylight
    to: dusklight
    id: BlokadaDziennaOFF

  # Tryb świąteczny
  - platform: state
    entity_id: !input swieta
    to: "on"
    id: SwietaON

  - platform: state
    entity_id: !input swieta
    to: "off"
    id: SwietaOFF

actions:
  - choose:

      # 🟢 TRYB: PODBITKA WIECZOREM
      - conditions:
          - condition: trigger
            id: PodbitkaON
          - condition: template
            value_template: "{{ not (tryb_swieta_aktywny | default(false)) }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - !input podbitka_rogi
                - !input podbitka_srodki
          - variables:
              tryb_podbitka_aktywny: true
          - wait_for_trigger:
              - platform: time
                at: !input godzina_podbitka_srodki_off
            continue_on_timeout: true
          - service: light.turn_off
            target:
              entity_id: !input podbitka_srodki
          - wait_for_trigger:
              - platform: time
                at: !input godzina_podbitka_rogi_off
            continue_on_timeout: true
          - service: light.turn_off
            target:
              entity_id: !input podbitka_rogi
          - variables:
              tryb_podbitka_aktywny: false

      # 🟢 TRYB: PODBITKA RANO
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: PodbitkaRANO
              - condition: trigger
                id: PodbitkaNightToDawn
          - condition: template
            value_template: "{{ not (tryb_swieta_aktywny | default(false)) }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - !input podbitka_rogi
                - !input podbitka_srodki
          - variables:
              tryb_podbitka_aktywny: true
          - wait_for_trigger:
              - platform: state
                entity_id: !input czujnik_dnia
                to: dawnlight
            continue_on_timeout: true
          - service: light.turn_off
            target:
              entity_id:
                - !input podbitka_rogi
                - !input podbitka_srodki
          - variables:
              tryb_podbitka_aktywny: false

      # 🟢 TRYB: PODJAZD PO BRAMIE
      - conditions:
          - condition: trigger
            id: BramaOPEN
          - condition: template
            value_template: "{{ not (tryb_podbitka_dzienny | default(false)) }}"
          - condition: or
            conditions:
              - condition: state
                entity_id: !input czujnik_dnia
                state: dusklight
              - condition: state
                entity_id: !input czujnik_dnia
                state: nightlight
              - condition: state
                entity_id: !input czujnik_dnia
                state: dawnlight
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input podjazd
          - delay:
              minutes: !input czas_swiecenia_podjazdu
          - service: light.turn_off
            target:
              entity_id: !input podjazd

      # 🟢 TRYB: PODBITKA PO BRAMIE
      - conditions:
          - condition: trigger
            id: BramaOPEN
          - condition: template
            value_template: "{{ not (tryb_swieta_aktywny | default(false)) and not (tryb_podbitka_dzienny | default(false)) and not (tryb_podbitka_aktywny | default(false)) }}"
        sequence:
          - delay: "00:00:30"
          - service: light.turn_on
            target:
              entity_id:
                - !input podbitka_rogi
                - !input podbitka_srodki
          - delay:
              minutes: !input czas_swiecenia_podbitki
          - service: light.turn_off
            target:
              entity_id:
                - !input podbitka_rogi
                - !input podbitka_srodki

      # 🟢 TRYB: PODBITKA PO DRZWIACH
      - conditions:
          - condition: trigger
            id: DrzwiOPEN
          - condition: template
            value_template: "{{ not (tryb_swieta_aktywny | default(false)) and not (tryb_podbitka_dzienny | default(false)) and not (tryb_podbitka_aktywny | default(false)) }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - !input podbitka_rogi
                - !input podbitka_srodki
          - delay:
              minutes: !input czas_swiecenia_podbitki
          - service: light.turn_off
            target:
              entity_id:
                - !input podbitka_rogi
                - !input podbitka_srodki

      # 🟢 TRYB: PODJAZD PO DRZWIACH
      - conditions:
          - condition: trigger
            id: DrzwiOPEN
          - condition: template
            value_template: "{{ not (tryb_podbitka_dzienny | default(false)) }}"
        sequence:
          - delay: "00:00:30"
          - service: light.turn_on
            target:
              entity_id: !input podjazd
          - delay:
              minutes: !input czas_swiecenia_podjazdu
          - service: light.turn_off
            target:
              entity_id: !input podjazd

      # 🟢 BLOKADA DZIENNA – ŚWIT → DZIEŃ
      - conditions:
          - condition: trigger
            id: BlokadaDziennaON
        sequence:
          - variables:
              tryb_podbitka_dzienny: true

      # 🟢 BLOKADA DZIENNA OFF – ZMIERZCH
      - conditions:
          - condition: trigger
            id: BlokadaDziennaOFF
        sequence:
          - variables:
              tryb_podbitka_dzienny: false

      # 🎄 TRYB: ŚWIĘTA – blokada podbitki
      - conditions:
          - condition: trigger
            id: SwietaON
        sequence:
          - variables:
              tryb_swieta_aktywny: true

      # 🎄 TRYB: ŚWIĘTA OFF – przywrócenie normalnego działania
      - conditions:
          - condition: trigger
            id: SwietaOFF
        sequence:
          - variables:
              tryb_swieta_aktywny: false
